[project]
name = "project-root"
version = "0.1.0"
description = "Monorepo root for Frontend and Backend"
requires-python = ">=3.10"

# This tells uv to look inside the backend folder for a Python project
[tool.ruff.lint]
select = ["I", "E", "F", "W"]

[tool.uv.workspace]
members = ["backend"]

[tool.mypy]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "celery.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "joblib.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "sklearn.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "torch.*"
ignore_missing_imports = true
